#!/bin/bash
scripts/release
echo "copying release/dashboard_cljs.js to ../dashboard-service/src/public/js/"
cp release/dashboard_cljs.js ../dashboard-service/src/public/js/
echo "copying resources/css/dashmap.css to ../dashboard-service/src/public/css/"
cp resources/css/dashmap.css ../dashboard-service/src/public/css/
